[versions]
kotlin = "1.8.10"
agp = "8.0.2"
javapoet = "1.13.0"

[libraries]
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet" }