name: Run Static Analysis

on:
  push:
    branches: [master, 1.x, ci]
  pull_request:
    branches: [master, 1.x, ci]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run static analysis
        uses: natiginfo/action-detekt-all@1