name: Run Unit Tests

on:
  push:
    branches: [master, ci]
  pull_request:
    branches: [master, ci]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - run: chmod +x gradlew
      - name: Unit test
        run: |
          ./gradlew clean
          ./gradlew test