name: Run Unit Tests

on:
  push:
    branches: [master, 1.x, ci]
  pull_request:
    branches: [master, 1.x, ci]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Unit test
        run: |
          ./gradlew test